# Generated by Django 3.2.7 on 2021-09-27 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Покупатель')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('data_add', models.DateField(default=datetime.date(2021, 9, 27), verbose_name='Дата начала')),
                ('date_end', models.DateField(default=datetime.date(2022, 9, 27), verbose_name='Дата конца')),
                ('cover', models.FileField(upload_to='images/', verbose_name='Документы')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ('date_end',),
            },
        ),
    ]
