# Generated by Django 3.2.7 on 2021-10-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updocks', '0004_auto_20211006_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover2',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='images/', verbose_name='Документыs'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='images/', verbose_name='Документы'),
        ),
    ]
