# Generated by Django 3.2.7 on 2021-10-10 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updocks', '0008_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar', 'RAR', 'ZIP', '7z', '7Z'])], verbose_name='Дополнительные файлы в архиве'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Документы'),
        ),
    ]
